### ISSUE TITLE
How to train the QG model？

### ISSUE THREAD

**Issue by Apollo2Mars** [roemmele/answerquest#4]
Hello, I haven't seen any training script about QG. Can you explain how this QG is trained？

**Comment by roemmele** [comment]
Thanks for asking about this - I'm in the process of getting this code into the repo. The QG model is fully trained using the OpenNMT-py library, but there some specific steps needed to prepare a dataset for training. I'll send you an update when I have this ready.

**Comment by TccccD** [comment]
Hello, I also want to know how to train the QG model, when can you provide it, or provide a simple version. Thanks! @roemmele

**Comment by roemmele** [comment]
Hi @Apollo2Mars and @TccccD, I added some files and instructions for training the QG model in scripts/question_generation. There's a tiny bit of sample data in that directory to illustrate the process - if you're looking for the full SQuAD/NewsQA data we used for the published models, let me know. When you have the chance to try it out let me know if there's any issues. Thanks!

**Comment by TccccD** [comment]
> Hi @Apollo2Mars and @TccccD, I added some files and instructions for training the QG model in scripts/question_generation. There's a tiny bit of sample data in that directory to illustrate the process - if you're looking for the full SQuAD/NewsQA data we used for the published models, let me know. When you have the chance to try it out let me know if there's any issues. Thanks!

Thanks!
