### ISSUE TITLE
Can't create QnAPipeline object

### ISSUE THREAD

**Issue by gabriead** [roemmele/answerquest#6]
Hi @roemmele,
I followed the installation instructions (clone and install the repo, downloading the models) and tried to create a QnAPipeline. However the module 'QnAPipeline' can not be found and also does not seem to exist in the repo. Can you help me out?
I have attached a screenshot with the current path and code

<img width="589" alt="folder-structure" src="https://user-images.githubusercontent.com/9105222/164447721-4f5b3664-4aca-44e6-8246-939c8e6d0a40.png">

**Comment by gabriead** [comment]
Could fix the import issue but now having trouble with onmt (see screenshot). Do you have a conda environment that you could share, where all the dependencies are available?
<img width="495" alt="folder-structure" src="https://user-images.githubusercontent.com/9105222/164473540-4cd16b00-b6a7-46d1-bdb0-0bc0fcb179d5.png">

**Comment by roemmele** [comment]
Hi! Someone else reported an issue with installing the library in versions of Python later than 3.6. Can you try creating a Python 3.6 env, and then running "pip install ." on the top level of the repo so that it will read the specific dependencies listed in setup.py?

**Comment by gabriead** [comment]
Hi @roemmele, I have change the conda env to Python 3.6 and now it works. Thank you very much!

**Comment by roemmele** [comment]
Glad to hear that worked! I'll update the README to indicate the Python 3.6 requirement. I'd like to eventually figure out why this doesn't work with more recent versions, I just haven't had time. Thanks!
